# 1. 守护进程主配置（必须有）
[supervisord]
nodaemon=true               # Docker 部署必须为 true
user=root
logfile=/dev/null           # 日志直接打到 Docker stdout，这里设为 null
logfile_maxbytes=0

# 2. 进程双向通信协议
[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

# 3. 本地 Unix 套接字服务（客户端和守护进程沟通的桥梁）
[unix_http_server]
file=/var/run/supervisor.sock
chmod=0700
username=sc
password=123456

# 4. 客户端工具配置（你报错的根源：它需要知道去哪里找上面的 sock 文件）
[supervisorctl]
serverurl=unix:///var/run/supervisor.sock
username=sc
password=123456

[program:test]
directory=/app
command=bun run test.ts
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0