version: '3'
services:
  rabbit:
    # 本地自定义的镜像
    container_name: rabbitmq-custom
    image: rabbitmq:3.10-management
    restart: always
    networks:
      - allinone
    ports:
      - "0.0.0.0:5672:5672"
      - "0.0.0.0:15672:15672"
    environment:
    ### 貌似没用要手动进终端添加用户和权限
      - RABBITMQ_DEFAULT_USER=dev
      - RABBITMQ_DEFAULT_PASS=111111

networks:
  allinone:
    external: true