version: "3"
services:
  nginx:
    container_name: nginx-demo
    image: nginx:alpine
    restart: always
    ports:
      - 8080:80
      - 8443:443
      - 8090:8090
    volumes:
      - ./html/:/usr/share/nginx/html/
      - ./conf/:/etc/nginx/conf.d/
      - ./certs/:/etc/nginx/certs/
      - ./log/:/var/log/nginx/
      - ./nginx.conf:/etc/nginx/nginx.conf
     
