version: '3'
services:
  rabbit:
    container_name: mq-demo
    image: rabbitmq-custom
    restart: always
    networks:
      - allinone
    ports:
      - "0.0.0.0:5672:5672"
      - "0.0.0.0:15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=dev
      - RABBITMQ_DEFAULT_PASS=0nPq!RG3x#mcp@Rt0

networks:
  allinone:
    external: true