# Use root/example as user/password credentials
version: '3'

services:
  # mongo:
  #   image: mongo:4
  #   restart: always
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: root
  #     MONGO_INITDB_ROOT_PASSWORD: 123456
  #     MONGO_INITDB_DATABASE: yapi
  #   volumes: 
  #       - ./mongo-conf:/docker-entrypoint-initdb.d
  #       - ./mongo/etc:/etc/mongo
  #       - ./mongo/data/db:/data/db
  #   ports: 
  #       - 27018:27017
  #   healthcheck:
  #     test: ["CMD", "netstat -anp | grep 27017"]
  #     interval: 2m
  #     timeout: 10s
  #     retries: 3
  yapi:
    build:
      context: ./
      dockerfile: Dockerfile
    image: yapi
    # 第一次启动使用
    # command: "yapi server"
    # 之后使用下面的命令
    command: "sh /home/run.sh"
    volumes: 
        - ./run.sh:/home/run.sh
        - ./my-yapi:/my-yapi
        # - ./server.js:/usr/local/lib/node_modules/yapi-cli/src/commands/server.js
    ports: 
      - '${SERVER_PORT}:9090'
      - '${WEB_PORT}:3000'
    networks: 
      - allinone
    external_links: 
      - mongo-demo
    # depends_on:
    #   - mongo

networks: 
  allinone:
    external: true

# apk add vim
# cd /usr/local/lib/node_modules/yapi-cli/src/commands
# 增加 authSource 配置