version: "3"
services:
  mongo:
    container_name: mongo-demo
    image: mongo
    restart: always
    networks:
      - allinone
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=123456
    volumes:
    #  - ./db:/data/db/
      - ./log:/data/log/
      - ./backup:/data/backup
      - ./mongo.conf:/etc/mongo/mongod.conf
    #  - ./cmd.sh:/home/cmd.sh
    ports:
      - "127.0.0.1:27017:27017"
      - "0.0.0.0:27016:27017"
  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    depends_on: 
      - mongo
    networks:
      - allinone
    ports:
      - 8081:8081
    links:
      - mongo
    environment:
      # mongo-express 验证
      - ME_CONFIG_BASICAUTH_USERNAME=root
      - ME_CONFIG_BASICAUTH_PASSWORD=123456
      # 数据库管理员
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=123456
      - ME_CONFIG_MONGODB_SERVER=mongo-demo
# docker network create allinone
networks:
  allinone:
    external: true
