version: '3'
services:
  redis-master: 
    image: redis:alpine
    container_name: redis-demo
    restart: always
    command: redis-server --requirepass 123456
    ports:
      - 6379:6379
    volumes:
      - ./data:/data
